version: '3'
services:
  mysql56:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql-container3
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fadel123
    volumes:
      - /var/lib/mysql56-data:/var/lib/mysql