version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mysql56:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql-container2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - /var/lib/mysql56-data:/var/lib/mysql